### ISSUE TITLE
为什么我引入了之后，箭头图标没有出来呢

### ISSUE THREAD

**Issue by wuyanwen** [liujians/Wa-UI#1]

**Comment by liujians** [comment]
2800的改版让小程序不再支持css的import，而且小程序本身也没有开放引入外部font文件的编译，请暂时使用图片替代iconfont，后续开放了引入font文件会第一时间更新项目，谢谢反馈

**Comment by jonahfang** [comment]
可以使用 iconfont(阿里巴巴矢量图标库），参见:

https://github.com/ly272864/wechat-app-ipinbb/issues/1
