### ISSUE TITLE
在最新的v0.10.102700开发工具中，界面显示不正常

### ISSUE THREAD

**Issue by jonahfang** [liujians/Wa-UI#2]
好像不再支持 @import '//cdn.bootcss.com/ionicons/2.0.1/css/ionicons.css';

**Comment by ghost** [comment]
对的，我也遇到了这个问题！

**Comment by wuyanwen** [comment]
是的，不支持了，希望尽快修复下

**Comment by liujians** [comment]
2800的改版让小程序不再支持css的import，而且小程序本身也没有开放引入外部font文件的编译，请暂时使用图片替代iconfont，后续开放了引入font文件会第一时间更新项目，谢谢反馈

**Comment by jonahfang** [comment]
可以使用 iconfont(阿里巴巴矢量图标库），参见:

```
https://github.com/ly272864/wechat-app-ipinbb/issues/1
```
